

const db = require("coders.db")
const fs = require("fs");
const express = require("express");
const bodyParser = require("body-parser");
const app = express();
const http = require('http');

app.use(express.static("public"));
var options = [
  "İyidir sen?",
  "Hmm",
  "Hmm keme oh just",
  "Hae pwalo nEas",
  "Amerrika birleşik cleverBOT",
  "Sensin ben im en drin",
  "Drink drink. yummy",
  "Fr pornhub",
  "Tag proo”",
  "Oh my god tanrım :)",
  "ruski papraska",
  "I love you",
  "Sensin",
  "İyi sen?",
"Hello",
  "Salak sın oç musun ya la aw yeyer oc uswm yeter rbe aja 123”,",
  "ĞÜQWRTYZ JOJUK",
  "WHİTE NİGGAHS",
  "seb nura lous",
  "sagopa ceza küsmüş saat tarih: 1968 | 4 Tl",
  "Yetmiş elliymiş",
  "Espiri yapiam mi",
  "Discord.js www.com",
  "Salak sensin amm",
  "Nsmskw wksla wkx",
  "S≠",
  "KAKA YE",
  "Yalıcam aç sikini",
  "OÇ NAMASTE.",
  "hello",
  "Ok.",
  "Boş türkiye.",
  "nefret ediyorum sendende",
"Aqbitti",
  "-A-s- -h-g- *ma79l.",
  "Oç salak kebap yemelisin!",
  "İyiyim siz",
  "Nefret duydum",
  "Dedem öldü ya",
  "Âjşjşwlö Nedkap",
  "sakat oç",
  "Hayin sensin",
  "Yoo nsıl",
  "Kes sikerim",
  "Nedir αυτό",
  "Ha",
  "Sen","Misin",
  "yokki",
  "eMe!a",
  "τα δικα σου",
  "Imanq",
  "levql",
  "Kiso dregustia ",
  "Pornocu olmaya nedersin?",
  "Senle olalım biz",
  "aynennn.",
  "deleted of yarran",
  "Yok bnde.",
  "Scourge of delete",
  "Deleteof kankam",
  "SEA ASE",
  "Mal mısın????",
  "Hello!",
  "Netrestoa.com",
  "Hop yavaş",
  "Çocda",
  "nED",
  "ne",
  "yeter be",
  "Što je",
  "oç kafa",
  "dana kebap olmalı",
  "€ 60$",
  "Woa",
  "Whats up ana skm",
  "İlkokul harika",
  "Orta öğretim harika",
  "Ahahahhah ne",
  "Nea8.",
  "Inanma banane",
  "Nuri ben",
  "taşşak",
  "Ne Diyorsun.",
  "Yapaydız.",
  "EVLQEKVQK.",
  "İyi murat sen nabıon",
  "aİsmim kimki",
  "Bu kesin.",
  "Kesinlikle.",
  "Umarım kesin sensindir.",
  "Just pwer melaoş",
  "Şüphesiz rahat durt.",
  "Ananı sikmek istiyorum.",
  "KES LAN",
  "Evet kesinlikle.",
  "Güvenebilirsiniz.",
  "Gördüğüm kadarıyla evet.",
  "Büyük ihtimalle.",
  "Aç koynunu",
  "İyi.",
  "Evet.",
  "İşaretler evet'e işaret ediyor.",
  "Vay be",
  "Buna güvenme.",
  "Cevabım hayır.",
  "Kaan şüphesiz nefret benden",
  "Aç koynunu giricem",
  "Salak salak",
  "Covid19 +- www.ownerCovid18.com.tr *+() ayok)",
  "Köpekim var",
  "Carl ben",
  "Olmuyor sıkıcı",
  "My, you new dog",
  "Bozuksun.",
  "Kankamm.",
  "NeOLUYOR.",
  "Sen kimsin?.",
  "Olur.",
  "Sg",
  "tANIMIYORUM.",
  "EV.",
  "Kaynaklarım hayır diyor.",
  "Outlook çok iyi değil.",
  "Katabe oh no wyf",
  "What?",
  "No ehat pls aj",
  "Aj da hdwu uhda p",
" js KKQ LA neo",
  "En iyisi sensin ki",
  "Noluyor sena",
  "AYŞE BAPA CEH S",
  "Çok şüpheli.",
  "Bulanık cevap tekrar deneyin.",
  "Sonra tekrar sor.",
  "nobody answered my question.",
  "Sana şimdi söylememek daha iyi.",
  "Robot",
  "o amq.",
  "Robotsam sanane",
  "Yeter.",
  "Ayşe",
  "Salih misin.",
  "Oh msg at",
  "Teşekkürler siz?",
  "Bu inanılmaz :)",
  "Selam",
  "Evet kanka.",
  "Kanka",
  "Aleyna gilki la.",
  "Lan.",
  "Kes.",
  "Şimdi tahmin edemem.",
  "Konsantre ol ve tekrar sor.",
  "Kesinlikle Adamın Dibi O.",
  "Gel beraber am",
  "Aleyküm selam.",
  "11 + 11 kaç?.",
  "Tanımıom ki.",
  "Olamaz ki.",
  "Ne.",
  "Ne istiyorsun?.",
  "OÇ.",
  "NEE.",
"meme aç.",
  "geliyorum.",
  "nE.",
  "Açsana",
  "Memeni",
  "Mal.",
  "Fuck.",
  "No old man.",
  "Olamaz.",
  "Old",
  "Nahrı",
  "Older man",
  "Man",
  "Spotify güzeldir",
  "Outlook ne",
  "Yok",
  "Yo",
  "Seaasıkr","nekos.life je ljubav",
  "Ölsün",
  "Öl",
  "Geber",
  "Kafir oç",
  "nekos.life is love <3",
  "OkKO.",
  "O KK .",
  "nana",
  "selandırea",
  "wlander io",
  "modülüm",
  "discord js v12 pro edition no guide of server pro giriş yap",
  "Düzgünüm zaten",
  "Sende değilsin",
  "Epic games.com",
  "1*50 Kaç tl?",
  "Türküm",
  "Ayşe.",
  "Namık oç.",
  "KAVGA VAR!",
  "EA GAMES.",
  "Nerde.",
  "Bulamadım.",
  "Şaka yaptım",
  "Namık jemal",
  "Şaka",
  "GTA5 Mİ.",
  "ÜCRETSİZ KNK.",
  "ADAM.",
  "SEVİYORUM SENİ.",
  "muck",
  ":hearts:",
  "kALP OLSA SEVGİ NE",
  "Nedir sevgi",
  "İyi sen?",
  "o mg",
  "idiot.",
  "ne nedir bildirmece",
  "sevgi var!",
  "eeee",
  "Ee noluyor kankam",
  "Pff boş",
  "Asker YAT AŞŞA",
  "BODY PARSER EXTENDED TRUE",
  "Mozilla firefox. güzel",
  "Ay kuçu kuçu",
  ":( üzüldüm..",
  "CEVAp boŞ."
];

let iyiMSN = ["İyidir sen","Sen nasılsın","Hiç aynı.","Sen?","Sensiz kötüyüm :("]

let random = Math.floor(Math.random() * iyiMSN.length);

var iyiMSNsorular = 
[
"Naber",
"Nasılsın",
"İyi misin",
"Hayat nasıl",
"Napıyon",
"Nabıon",
"Napıon",
"Nabıyon",
"naber",
"nasılsın",
"iyi misin",
"hayat nasıl",
"nabıon",
  "napıon",
  "nabıyorsun",
  "napıyorsun",
  "Napıyon",
"Napıyorsun",
]
app.use(express.static("public"));

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.get("/", (request, response) => {
  response.send("<center><bold>Hello world!</bold></center>");
});

app.post("/question/codersbots", function(req, res) {
  let yanit;
  let soru = req.body.question
if(soru){
      var num = soru.length + 3 % options.length *1
    yanit = options[num];

  
  
  if(soru.includes(iyiMSNsorular)) yanit = iyiMSN[random]
  console.log(`${soru} => ${yanit}`)   
  res.veri = {
    yanit:yanit+"."
  }
  req.veri={
    yanit:yanit+"."
  }
  res.json(res.veri||req.veri)
}
})

const listener = app.listen(process.env.PORT, () => {
  console.log("Your app is listening on port " + listener.address().port);
});